version: "3"
services:
  onlyoffice:
    image: onlyoffice/documentserver:latest
    container_name: onlyoffice-document-server
    ports:
      - "80:80"
    environment:
      - JWT_SECRET=my_jwt_secret
    volumes:
      - ./fonts:/usr/share/fonts/truetype/custom
      # - ./local.json:/etc/onlyoffice/documentserver/local.json
