version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx
    stdin_open: true
    tty: true
    restart: always
    ports:
     - 80:80
     - 443:443
    networks:
     - onlyoffice
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf
  owncloud:
    container_name: owncloud-server
    image: owncloud:latest
    stdin_open: true
    tty: true
    restart: always
    expose:
     - '80'
     - '443' 
    networks:
     - onlyoffice
    volumes:
     - owncloud_data:/var/www/html
     - ./onlyoffice:/var/www/html/apps/onlyoffice
  mysql:
    container_name: owncloud-mysql
    image: mariadb
    restart: always
    expose:
     - '3306'
    networks:
     - onlyoffice
    environment:
      - MYSQL_ROOT_PASSWORD=i
      - MYSQL_DATABASE=owncloud
      - MYSQL_USER=owncloud_user
      - MYSQL_PASSWORD=i
    volumes:
      - mysql_data:/var/lib/mysql
  onlyoffice-document-server:
    container_name: onlyoffice-document-server
    image: onlyoffice/documentserver:latest
    stdin_open: true
    tty: true
    restart: always
    networks:
      - onlyoffice
    expose:
      - '80'
      - '443'
    volumes:
       - document_data:/var/www/onlyoffice/Data
       - document_log:/var/log/onlyoffice
networks:
  onlyoffice:
    driver: 'bridge'
volumes:
  document_data:
  document_log:
  owncloud_data:
  mysql_data:
